### PR TITLE
Adds babel for supporting older node versions

### PR DESCRIPTION
**Pull request by laardee**
This PR adds babel to npm publish flow for supporting projects that are made with older node versions e.g. for AWS Lambda (node 4.3.2) and using node-wit as a library.

Relates to issues https://github.com/wit-ai/node-wit/issues/88, https://github.com/wit-ai/node-wit/issues/69 (and partly https://github.com/wit-ai/node-wit/issues/94)

### CODE REVIEW

**Comment by smatjes** [comment]
Would be great if this gets pulled. Would help me a lot with a current project.

**Comment by laardee** [comment]
@patapizza, is there any change this (or something similar) could be merged?

**Comment by stopachka** [comment]
cc @blandinw for thoughts too

I am not sure how we should proceed with introducing babel. This is definitely good for supporting older npm versions, but it does add complexity costs for the library.

Since we only use arrow functions and destructuring, for a few hundred line files, I think it would be simpler to avoid using them, rather then introducing babel, if we want to support older npm versions

this was the issue I opened to get thoughts on the problem -- https://github.com/wit-ai/node-wit/issues/69

**Comment by laardee** [comment]
@stopachka @blandinw, I think only problem is the destructuring, because node v4.0 supports lots of ES6 features (second paragraph https://nodejs.org/en/blog/release/v4.0.0/) and LTS maintenance for node v0.12 will end at the end of the year (https://github.com/nodejs/LTS)

Babel was the easy way out, but I can remove the Babel from this PR and change destructuring parts from the code if that would be better.

I need the node v4.3.2 support (AWS Lambda), because we use node-wit in our Serverless workshops (https://sc5.io/posts/introducing-sc5-serverless-bot-workshop/) and now I have to use my own fork.

**Comment by blandinw** [comment]
@stopachka @laardee I'd rather go with simplicity too.
That being said, ES6 offers a lot of niceties and I think we can centralize the complexity a bit more.

How about having a `publish.sh` script along the lines of:

```
#!/bin/bash

set -ex

mkdir dist
cp package.json dist
babel lib --out-dir dist/lib
babel index.js --out-file dist/index.js
(
  cd dist
  npm publish
)
rm -rf dist
```

and keep .babelrc and updated package.json from this PR?
The rest of the code would be unchanged.

**Comment by laardee** [comment]
@stopachka @blandinw, something like this? I removed the bin folder and added the publish.sh.

I also added a few mocha tests for testing the functionality. For running the tests agains wit.ai app, there is a zip that contains simple app that can be used to create a test app in https://wit.ai. To test /lib locally, use `WIT_TOKEN=XXX npm test`. I also included .travis.yml if you wish to use CI, in there you just need to add the WIT_TOKEN as environmental variable.

Same applies to publish.sh, I added line before publishing the package that runs tests agains babelized files, therefore you need to run the publish.sh with token `WIT_TOKEN=XXX ./publish.sh`.

**Review by stopachka — APPROVED** [review]
great job!

**Comment by laardee** [comment]
@stopachka thanks 😄

**Pull request merged**
