### PR TITLE
Async Callbacks

### PR DESCRIPTION
**Pull request by DiegoRBaquero**

### CODE REVIEW

**Comment by patapizza** [comment]
Thanks!

**Comment by DiegoRBaquero** [comment]
@patapizza Hadn't used ES6 and just realized I could have done `process.nextTick(cb(..));` instead of putting them inside a function.

It can be useful if you want to defer something else too along with the callback:

``` js
process.nextTick(() -> {
  console.log('Callback fired');
  cb(..);
});
```

 but if not it makes sense to just do 

``` js
 process.nextTick(cb(...))
```

Would you like me to keep it the way it is or clean it to single line?

**Comment by patapizza** [comment]
Wouldn't this fire the callback before actually calling `process.nextTick`?
Let's leave it as is.

**Comment by DiegoRBaquero** [comment]
Currently:

``` js
process.nextTick(() -> {
  cb(..);
});
```

is exactly the same as:

``` js
process.nextTick(cb(...))
```

which looks cleaner, imo. And alright :) thanks for reviewing my PR

**Comment by blandinw** [comment]
@DiegoRBaquero you're calling `cb()` before `process.nextTick` in the second case.
Am I missing something?

**Comment by DiegoRBaquero** [comment]
@blandinw Not really, cb() is being deferred to the next loop execution: https://nodejs.org/api/process.html#process_process_nexttick_callback_arg

**Comment by blandinw** [comment]
@DiegoRBaquero I think you meant `process.nextTick(cb)` then, instead of `process.nextTick(cb())`

**Comment by DiegoRBaquero** [comment]
You guys are completely right. Nevermind me.

**Comment by blandinw** [comment]
@DiegoRBaquero anyway, thanks for your contribution!
Could you describe when this is needed? When do we not want the callback to be synchronous?

**Comment by DiegoRBaquero** [comment]
You'd always want the callbacks to be async, if there's nothing on the loop it will be called immediately anyways. I'm creating FB Messenger bots, as you know they have entries on the webhook post, the example they posted is sync-iterating over each entry and adding extra time for each call to wit, -until the sync callback fires to continue-, adds up. Making wit's callbacks async I was able to speed up all the entries while not blocking express. This is just an example, but generally is better to not block execution of the rest of the program, even by few ms.

**Comment by blandinw** [comment]
> This is just an example, but generally is better to not block execution of the rest of the program, even by few ms.

Just to be clear, this does not block the execution of the program. The HTTP call is using Node's async I/O.

> I'm creating FB Messenger bots, as you know they have entries on the webhook post, the example they posted is sync-iterating over each entry and adding extra time for each call to wit, -until the sync callback fires to continue-, adds up

I understand your problem, but this is specific to your use case. Some people might want to have "synchronous" execution of their callback. This diff forces the call to be asynchronous. It is always better to leave the choice to the caller/user of library.
You can fix it for your use case by doing the call to `process.nextTick` in the "synchronous" callback.

After thinking more, I'm probably going to revert your diff to leave the choice to the caller instead of forcing async. Sounds good?

**Comment by DiegoRBaquero** [comment]
Yeah, sounds good :)

**Pull request merged**
